language: python
python: '2.7'
install:
- python bootstrap.py
- ./bin/buildout -N -t 3 -c buildout_travis.cfg
script: bin/django test lfc.tests --settings=lfc_project.settings_travis
notifications:
  irc: "irc.freenode.org#django-lfc"
